### PR TITLE
The Apply Generator

### PR DESCRIPTION
**Pull request by iHDeveloper**
# The story behind it
image
This PR is inspired by @InventivetalentDev. And, the goal of it is to improve the laziness! 😄 

# Info
This PR aims at creating a generator called `ApplyGenerator`. The goal of the generator is to copy code from a certain file and apply it safely in the middle of the file using placeholders. Instead of copying from `_functions.ts` and apply it to `Spiget.ts`. The generator can do that process for you faster and efficiently. 😎 

This unique generator will open the opportunity to update the library automatically when the API releases a new update. So, you can just relax and let the generator do the work on the update for you. 😇 

# Get Started
- Clone [My Fork](https://github.com/iHDeveloper/spiget-typescript) from branch `the-apply-generator`
- Update the dependencies by executing `npm ci`
- (Optional) Apply the functions `npm run apply-functions`
- Try it out 🙂 

# Checklist
- [x] Plan how the generator will work
- [x] Implement the generator
- [x] Optimize the generator
- [x] (Fix) Check if the start placeholder has the name that was included with the generator
- [x] (Fix) Assuming any placeholder that starts with "E" will be the end, and "G" will be the start
- [x] **EDIT:** Generate types import from `_imports.txt` into `Spiget.ts`
- (Optional) When the **Github Workflow** receives an update from [Spiget Documentation](https://github.com/SpiGetOrg/Documentation).
- - Update the documentation submodule
- - Generate the types of that update
- - Apply the new update
- - (Optional) Make a pull request to review the changes

Now the update becomes more automated and you just need to review it yay! :D

**EDIT:** No need to detect updates from [Spiget Documentation](https://github.com/SpiGetOrg/Documentation). 
> Though automated builds when the docs update shouldn't be needed, since those rarely require any updates c:
> 
> @InventivetalentDev 

# Try it out
We will test the apply generator on the new update in [Spiget Documentation](https://github.com/SpiGetOrg/Documentation/commit/4c344c592e3c5752549ba52ae9f8345fea377ab9). 

> **I recommend you to try this in `test` branch to avoid any problem that could cause damage to the repository** ⚠️ 

If you apply for the first time, spaces will be shown in the `Spiget.ts` that's because I didn't commit that change
So, commit it to see the new update changes very clear 😅 
- Check out to a new test branch by executing `git checkout -b test`
- Generate the types by execute `npm run generate-types` ( to remove the `class Path {}` in the `_functions.ts` )
- Apply the functions `npm run apply-functions`
- Commit the change `git add . && git commit -m "anything"`

Now, we will apply the new update changes to `Spiget.ts` 😁 
- cd `spiget-documentation/` and pull the changes `git pull origin master`
- Apply the functions `npm run apply-functions`
- Check out the changes `Spiget.ts`

# Bug Fixes
- (9a5a37b) Better and optimized way to find placeholders

# Screenshots
image

### CODE REVIEW

**Comment by InventivetalentDev** [comment]
Oh this is great! :D  
Though automated builds when the docs update shouldn't be needed, since those rarely require any updates c:

**Comment by iHDeveloper** [comment]
It will be an automated library :D that maintains itself which is cool and unique. 😁

**Comment by iHDeveloper** [comment]
Also, I'm not good with Github workflow so I'm not sure how to listen to push events from another repository 😅

**Comment by iHDeveloper** [comment]
The only way I found was making the documentation repository send a webhook event that triggers this repository

**Comment by iHDeveloper** [comment]
Included the apply from `_imports.txt` to `Spiget.ts`. Also, Support multiple placeholders in one target file in the generator.

I changed the script `apply-functions` to `apply` since it doesn't apply functions only anymore. Also, I regenerated the types and apply them to make sure everything is working. 👍 

This PR is ready to be merged 😁

**Pull request merged**
